name: 'Multistage'

trigger:
  - master

pr:
  - '*'

variables:
  BuildConfiguration: 'Release'
  Project: 'FIAP.Hackathon.OES.User.API/FIAP.Hackathon.OES.User.API.csproj'
  DockerfilePath: 'FIAP.Hackathon.OES.User.API/Dockerfile'
  ImageName: 'fiap-oes-user-api'
  ImageTag: '$(Build.BuildId)'

pool:
  name: 'SelfHostedPool'

stages:

- stage: Build
  displayName: 'Build e Geração da Imagem Docker'
  jobs:
  - job: BuildJob
    displayName: 'Build Docker Image'
    steps:
    - checkout: self
      clean: true

    - task: UseDotNet@2
      displayName: 'Use .NET SDK 8.x'
      inputs:
        packageType: 'sdk'
        version: '8.x'
        includePreviewVersions: false

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '$(Project)'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(Project)'
        arguments: '-c $(BuildConfiguration) --no-restore'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        dockerfile: '$(DockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
        repository: '$(ImageName)'
        tags: |
          $(ImageTag)
          latest

    - script: |
        docker images | findstr $(ImageName)
      displayName: 'Listar imagem gerada'